### ISSUE TITLE
Add cron job to AspectCronJobs twiki

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3_tools#20]
Regular processing with skare3_tools should be added here:

https://occweb.cfa.harvard.edu/twiki/Aspect/AspectCronJobs

**Comment by javierggt** [comment]
I do not think these are stable or "official" in any way, but I added them there.

To reproduce them you first have to create the corresponding conda environment which is not stable. For example: skare3_helpers, which is used for all these, is not even on skare3: sot/skare3/pull/326

Also, these processes use bash scripts that are very simple but some are not on github yet.

**Comment by javierggt** [comment]
Just realized this is still open, but the current cron jobs are added to that page already.
