### ISSUE TITLE
ska_testr needs to be updated as part of the test workflow

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3_tools#48]
The current dashboard is showing unexpected failures for two packages: Ska.ParseCM and cmd_states, both coming from the FutureWarning emitted by Ska.ParseCM.

- Ska.ParseCM is no longer a package in ska_testr.
- Chandra.cmd_states in ska_testr (test_unit.py) has code to prevent that warning (https://github.com/sot/ska_testr/blob/b9bd142e276fc3f79a5281698179241a3fde3b84/packages/Chandra.cmd_states/test_unit.py). This package passes when I run locally.

So I am just confused.

**Comment by jeanconn** [comment]
Looks to me like the dashboard runs ska_testr out of /export/jgonzale/ska_testr which has

https://github.com/sot/ska_testr/commit/8092f9a5a7ad2036fcc962006602def7796f12da

**Comment by javierggt** [comment]
Jean got it. I need to update that, or include the update in the process.

**Comment by jeanconn** [comment]
Yeah, I was wondering if an auto-update of that might make sense.  I can't see a real downside.

**Comment by taldcroft** [comment]
I always assume ska_testr is being run from the latest master.

**Comment by javierggt** [comment]
Fixed aeons ago
