### ISSUE TITLE
dashboard cron task uses old versions of packages

### ISSUE THREAD

**Issue by javierggt** [sot/skare3_tools#60]
We discovered that some times the tests are run with older versions of packages. On October 4th, the proseco version used was `4.8.2.dev36+gea71105` when it should have been `4.8.2.dev52+g7a51393`. The issue comes from the way the environment is updated and the way conda is initialized. Currently, the testing code does something equivalent to (using the $SKA/bin/skare script):
```
eval `${SKA_bin}/flt_envs -shell sh`
conda env update -n ska3-masters --file ska3-masters.yaml
run_testr
```
In this case, the conda package seems to not be updated.

The following works:
```
eval "$(/export/jgonzale/github-workflows/miniconda3-shiny/bin/conda shell.bash hook)"
conda activate ska3-masters
conda env update -n ska3-masters --file ska3-masters.yaml
run_testr
```

**Comment by taldcroft** [comment]
Weird. Anyway, if it works then :+1:.

**Comment by jeanconn** [comment]
Interesting.  Without playing with it more, I'd guess that in the first method conda doesn't "know" it is in an env (probably set by some other var when you set the root conda and activate the env).  Wonder if it might work without the "env' in that case, but second method seems fine (unless you still need to set SKA for some tests to run).

**Comment by javierggt** [comment]
The thing with the second method is that it is not what the skare script does. I do not like having my own script hanging around, because then I have to make sure it is always there. What I can do is to figure out which environmental variable is required and add it to the skare script. Does that sound ok?

**Comment by jeanconn** [comment]
Regarding "What I can do is to figure out which environmental variable is required and add it to the skare script." I don't know what you mean.  The skare scripts have only been for production condas that have only been "root" conda environments.

**Comment by javierggt** [comment]
The problem is not that this is not a "root" environment. The problem is that the statement that initializes conda:
```
eval "$(/export/jgonzale/github-workflows/miniconda3-shiny/bin/conda shell.bash hook)"
```
must be setting some environmental variables that lets conda know "something" (as you pointed out above). The question is which variables are those. If I know, I can add them to the skare script which, as I mentioned above, is what I use to run.

**Comment by jeanconn** [comment]
I also don't know what "conda env update" does that is different from "conda update".

**Comment by jeanconn** [comment]
Basically, I'm just a little hesitant to update flt_envs to accommodate a testing funny.

**Comment by javierggt** [comment]
This seems old.

The way things are setup right now (for a few years) is that I have a script in the base environment called `conda_wrapper`, which has the following:
```
#!/bin/sh

condadir=$(realpath $(dirname $0))
eval "$(${condadir}/conda shell.bash hook)"
exec "$@"
```

and the crontab for updating ska3-masters is 
```
$CONDA_PREFIX/bin/conda_wrapper conda update -y -n ska3-masters --override-channels -c https://icxc.cfa.harvard.edu/aspect/ska3-conda/masters -c https://icxc.cfa.harvard.edu/aspect/ska3-conda/flight ska3-core-latest ska3-flight-latest ska3-perl-latest
```
