### ISSUE TITLE
docs workflow fails because SKA is not defined

### ISSUE THREAD

**Issue by javierggt** [sot/skare3_tools#67]
- sot/cmd_states
- sot/agasc
- sot/annie

**Comment by taldcroft** [comment]
Can you add `>>> os.envion['SKA'] = '/proj/sot/ska'` in beginning of the docs?  Or maybe I'm not understanding entirely.

**Comment by javierggt** [comment]
I posted this issue so I would not forget. I can add the SKA variable in the workflow, but a priori one (like me) does not know whether that is enough. A standard Ska environment defines a bunch of variables in `flt_envs`, and there might be parts that are skipped if some variable is not defined, and sphinx silently skips that part. I guessed that if it was using SKA, it was running the actual code, and what else might be needed then?

**Comment by taldcroft** [comment]
Packages should only absolutely require `SKA`. The other stuff in `flt_envs` is potentially relevant for some production tasks (I haven't reviewed this lately), but for standalone Ska3 the only requirement is `SKA`. We have had a number of discussions about this over the years and finally settled with that.  If you don't require `SKA` then it just introduces so many complications handling the case where there is no SKA.

**Comment by javierggt** [comment]
ok, good to know. That makes things simpler.

**Comment by taldcroft** [comment]
I looked again at flt_envs.  This is really all just stuff that is required for old-ish production code, sybase, etc.  We can't easily get rid of it, but standalone code does not (or should not) use it.  We have modern-day equivalents like:
```
if (not defined $ENV{SKA_ARCH_OS}) {
    chomp($ENV{SKA_ARCH_OS} = `python -c 'import sys; print(sys.prefix)'`);
}
```

**Comment by javierggt** [comment]
This has been fixed for quite a while.
